/*
 * This file is autogenerated by 'generate.py' script from risc-v.yaml file
 * Do not try to change anything in this file
 ***********************************************************
 * Written by Glaz Roman (Vokerlee)
 */

#ifndef SIMULATOR_INSTRUCTION_EXEC_INSTRUCTION_EXEC_H
#define SIMULATOR_INSTRUCTION_EXEC_INSTRUCTION_EXEC_H

#include "hart/hart.h"
#include "instruction.h"

namespace rvsim {
namespace iexec {

// clang-format off

Exception BEQ        (Hart *hart, const Instruction &instr);
Exception BNE        (Hart *hart, const Instruction &instr);
Exception BLT        (Hart *hart, const Instruction &instr);
Exception BGE        (Hart *hart, const Instruction &instr);
Exception BLTU       (Hart *hart, const Instruction &instr);
Exception BGEU       (Hart *hart, const Instruction &instr);
Exception JALR       (Hart *hart, const Instruction &instr);
Exception JAL        (Hart *hart, const Instruction &instr);
Exception LUI        (Hart *hart, const Instruction &instr);
Exception AUIPC      (Hart *hart, const Instruction &instr);
Exception ADDI       (Hart *hart, const Instruction &instr);
Exception SLLI       (Hart *hart, const Instruction &instr);
Exception SLTI       (Hart *hart, const Instruction &instr);
Exception SLTIU      (Hart *hart, const Instruction &instr);
Exception XORI       (Hart *hart, const Instruction &instr);
Exception SRLI       (Hart *hart, const Instruction &instr);
Exception SRAI       (Hart *hart, const Instruction &instr);
Exception ORI        (Hart *hart, const Instruction &instr);
Exception ANDI       (Hart *hart, const Instruction &instr);
Exception ADD        (Hart *hart, const Instruction &instr);
Exception SUB        (Hart *hart, const Instruction &instr);
Exception SLL        (Hart *hart, const Instruction &instr);
Exception SLT        (Hart *hart, const Instruction &instr);
Exception SLTU       (Hart *hart, const Instruction &instr);
Exception XOR        (Hart *hart, const Instruction &instr);
Exception SRL        (Hart *hart, const Instruction &instr);
Exception SRA        (Hart *hart, const Instruction &instr);
Exception OR         (Hart *hart, const Instruction &instr);
Exception AND        (Hart *hart, const Instruction &instr);
Exception ADDIW      (Hart *hart, const Instruction &instr);
Exception SLLIW      (Hart *hart, const Instruction &instr);
Exception SRLIW      (Hart *hart, const Instruction &instr);
Exception SRAIW      (Hart *hart, const Instruction &instr);
Exception ADDW       (Hart *hart, const Instruction &instr);
Exception SUBW       (Hart *hart, const Instruction &instr);
Exception SLLW       (Hart *hart, const Instruction &instr);
Exception SRLW       (Hart *hart, const Instruction &instr);
Exception SRAW       (Hart *hart, const Instruction &instr);
Exception LB         (Hart *hart, const Instruction &instr);
Exception LH         (Hart *hart, const Instruction &instr);
Exception LW         (Hart *hart, const Instruction &instr);
Exception LD         (Hart *hart, const Instruction &instr);
Exception LBU        (Hart *hart, const Instruction &instr);
Exception LHU        (Hart *hart, const Instruction &instr);
Exception LWU        (Hart *hart, const Instruction &instr);
Exception SB         (Hart *hart, const Instruction &instr);
Exception SH         (Hart *hart, const Instruction &instr);
Exception SW         (Hart *hart, const Instruction &instr);
Exception SD         (Hart *hart, const Instruction &instr);
Exception FENCE      (Hart *hart, const Instruction &instr);
Exception FENCE_I    (Hart *hart, const Instruction &instr);
Exception MUL        (Hart *hart, const Instruction &instr);
Exception MULH       (Hart *hart, const Instruction &instr);
Exception MULHSU     (Hart *hart, const Instruction &instr);
Exception MULHU      (Hart *hart, const Instruction &instr);
Exception DIV        (Hart *hart, const Instruction &instr);
Exception DIVU       (Hart *hart, const Instruction &instr);
Exception REM        (Hart *hart, const Instruction &instr);
Exception REMU       (Hart *hart, const Instruction &instr);
Exception MULW       (Hart *hart, const Instruction &instr);
Exception DIVW       (Hart *hart, const Instruction &instr);
Exception DIVUW      (Hart *hart, const Instruction &instr);
Exception REMW       (Hart *hart, const Instruction &instr);
Exception REMUW      (Hart *hart, const Instruction &instr);
Exception AMOADD_W   (Hart *hart, const Instruction &instr);
Exception AMOXOR_W   (Hart *hart, const Instruction &instr);
Exception AMOOR_W    (Hart *hart, const Instruction &instr);
Exception AMOAND_W   (Hart *hart, const Instruction &instr);
Exception AMOMIN_W   (Hart *hart, const Instruction &instr);
Exception AMOMAX_W   (Hart *hart, const Instruction &instr);
Exception AMOMINU_W  (Hart *hart, const Instruction &instr);
Exception AMOMAXU_W  (Hart *hart, const Instruction &instr);
Exception AMOSWAP_W  (Hart *hart, const Instruction &instr);
Exception LR_W       (Hart *hart, const Instruction &instr);
Exception SC_W       (Hart *hart, const Instruction &instr);
Exception AMOADD_D   (Hart *hart, const Instruction &instr);
Exception AMOXOR_D   (Hart *hart, const Instruction &instr);
Exception AMOOR_D    (Hart *hart, const Instruction &instr);
Exception AMOAND_D   (Hart *hart, const Instruction &instr);
Exception AMOMIN_D   (Hart *hart, const Instruction &instr);
Exception AMOMAX_D   (Hart *hart, const Instruction &instr);
Exception AMOMINU_D  (Hart *hart, const Instruction &instr);
Exception AMOMAXU_D  (Hart *hart, const Instruction &instr);
Exception AMOSWAP_D  (Hart *hart, const Instruction &instr);
Exception LR_D       (Hart *hart, const Instruction &instr);
Exception SC_D       (Hart *hart, const Instruction &instr);
Exception ECALL      (Hart *hart, const Instruction &instr);
Exception EBREAK     (Hart *hart, const Instruction &instr);
Exception URET       (Hart *hart, const Instruction &instr);
Exception SRET       (Hart *hart, const Instruction &instr);
Exception MRET       (Hart *hart, const Instruction &instr);
Exception DRET       (Hart *hart, const Instruction &instr);
Exception SFENCE_VMA (Hart *hart, const Instruction &instr);
Exception WFI        (Hart *hart, const Instruction &instr);
Exception CSRRW      (Hart *hart, const Instruction &instr);
Exception CSRRS      (Hart *hart, const Instruction &instr);
Exception CSRRC      (Hart *hart, const Instruction &instr);
Exception CSRRWI     (Hart *hart, const Instruction &instr);
Exception CSRRSI     (Hart *hart, const Instruction &instr);
Exception CSRRCI     (Hart *hart, const Instruction &instr);
Exception HFENCE_VVMA(Hart *hart, const Instruction &instr);
Exception HFENCE_GVMA(Hart *hart, const Instruction &instr);
Exception FADD_S     (Hart *hart, const Instruction &instr);
Exception FSUB_S     (Hart *hart, const Instruction &instr);
Exception FMUL_S     (Hart *hart, const Instruction &instr);
Exception FDIV_S     (Hart *hart, const Instruction &instr);
Exception FSGNJ_S    (Hart *hart, const Instruction &instr);
Exception FSGNJN_S   (Hart *hart, const Instruction &instr);
Exception FSGNJX_S   (Hart *hart, const Instruction &instr);
Exception FMIN_S     (Hart *hart, const Instruction &instr);
Exception FMAX_S     (Hart *hart, const Instruction &instr);
Exception FSQRT_S    (Hart *hart, const Instruction &instr);
Exception FADD_D     (Hart *hart, const Instruction &instr);
Exception FSUB_D     (Hart *hart, const Instruction &instr);
Exception FMUL_D     (Hart *hart, const Instruction &instr);
Exception FDIV_D     (Hart *hart, const Instruction &instr);
Exception FSGNJ_D    (Hart *hart, const Instruction &instr);
Exception FSGNJN_D   (Hart *hart, const Instruction &instr);
Exception FSGNJX_D   (Hart *hart, const Instruction &instr);
Exception FMIN_D     (Hart *hart, const Instruction &instr);
Exception FMAX_D     (Hart *hart, const Instruction &instr);
Exception FCVT_S_D   (Hart *hart, const Instruction &instr);
Exception FCVT_D_S   (Hart *hart, const Instruction &instr);
Exception FSQRT_D    (Hart *hart, const Instruction &instr);
Exception FADD_Q     (Hart *hart, const Instruction &instr);
Exception FSUB_Q     (Hart *hart, const Instruction &instr);
Exception FMUL_Q     (Hart *hart, const Instruction &instr);
Exception FDIV_Q     (Hart *hart, const Instruction &instr);
Exception FSGNJ_Q    (Hart *hart, const Instruction &instr);
Exception FSGNJN_Q   (Hart *hart, const Instruction &instr);
Exception FSGNJX_Q   (Hart *hart, const Instruction &instr);
Exception FMIN_Q     (Hart *hart, const Instruction &instr);
Exception FMAX_Q     (Hart *hart, const Instruction &instr);
Exception FCVT_S_Q   (Hart *hart, const Instruction &instr);
Exception FCVT_Q_S   (Hart *hart, const Instruction &instr);
Exception FCVT_D_Q   (Hart *hart, const Instruction &instr);
Exception FCVT_Q_D   (Hart *hart, const Instruction &instr);
Exception FSQRT_Q    (Hart *hart, const Instruction &instr);
Exception FLE_S      (Hart *hart, const Instruction &instr);
Exception FLT_S      (Hart *hart, const Instruction &instr);
Exception FEQ_S      (Hart *hart, const Instruction &instr);
Exception FLE_D      (Hart *hart, const Instruction &instr);
Exception FLT_D      (Hart *hart, const Instruction &instr);
Exception FEQ_D      (Hart *hart, const Instruction &instr);
Exception FLE_Q      (Hart *hart, const Instruction &instr);
Exception FLT_Q      (Hart *hart, const Instruction &instr);
Exception FEQ_Q      (Hart *hart, const Instruction &instr);
Exception FCVT_W_S   (Hart *hart, const Instruction &instr);
Exception FCVT_WU_S  (Hart *hart, const Instruction &instr);
Exception FCVT_L_S   (Hart *hart, const Instruction &instr);
Exception FCVT_LU_S  (Hart *hart, const Instruction &instr);
Exception FMV_X_W    (Hart *hart, const Instruction &instr);
Exception FCLASS_S   (Hart *hart, const Instruction &instr);
Exception FCVT_W_D   (Hart *hart, const Instruction &instr);
Exception FCVT_WU_D  (Hart *hart, const Instruction &instr);
Exception FCVT_L_D   (Hart *hart, const Instruction &instr);
Exception FCVT_LU_D  (Hart *hart, const Instruction &instr);
Exception FMV_X_D    (Hart *hart, const Instruction &instr);
Exception FCLASS_D   (Hart *hart, const Instruction &instr);
Exception FCVT_W_Q   (Hart *hart, const Instruction &instr);
Exception FCVT_WU_Q  (Hart *hart, const Instruction &instr);
Exception FCVT_L_Q   (Hart *hart, const Instruction &instr);
Exception FCVT_LU_Q  (Hart *hart, const Instruction &instr);
Exception FMV_X_Q    (Hart *hart, const Instruction &instr);
Exception FCLASS_Q   (Hart *hart, const Instruction &instr);
Exception FCVT_S_W   (Hart *hart, const Instruction &instr);
Exception FCVT_S_WU  (Hart *hart, const Instruction &instr);
Exception FCVT_S_L   (Hart *hart, const Instruction &instr);
Exception FCVT_S_LU  (Hart *hart, const Instruction &instr);
Exception FMV_W_X    (Hart *hart, const Instruction &instr);
Exception FCVT_D_W   (Hart *hart, const Instruction &instr);
Exception FCVT_D_WU  (Hart *hart, const Instruction &instr);
Exception FCVT_D_L   (Hart *hart, const Instruction &instr);
Exception FCVT_D_LU  (Hart *hart, const Instruction &instr);
Exception FMV_D_X    (Hart *hart, const Instruction &instr);
Exception FCVT_Q_W   (Hart *hart, const Instruction &instr);
Exception FCVT_Q_WU  (Hart *hart, const Instruction &instr);
Exception FCVT_Q_L   (Hart *hart, const Instruction &instr);
Exception FCVT_Q_LU  (Hart *hart, const Instruction &instr);
Exception FMV_Q_X    (Hart *hart, const Instruction &instr);
Exception FLW        (Hart *hart, const Instruction &instr);
Exception FLD        (Hart *hart, const Instruction &instr);
Exception FLQ        (Hart *hart, const Instruction &instr);
Exception FSW        (Hart *hart, const Instruction &instr);
Exception FSD        (Hart *hart, const Instruction &instr);
Exception FSQ        (Hart *hart, const Instruction &instr);
Exception FMADD_S    (Hart *hart, const Instruction &instr);
Exception FMSUB_S    (Hart *hart, const Instruction &instr);
Exception FNMSUB_S   (Hart *hart, const Instruction &instr);
Exception FNMADD_S   (Hart *hart, const Instruction &instr);
Exception FMADD_D    (Hart *hart, const Instruction &instr);
Exception FMSUB_D    (Hart *hart, const Instruction &instr);
Exception FNMSUB_D   (Hart *hart, const Instruction &instr);
Exception FNMADD_D   (Hart *hart, const Instruction &instr);
Exception FMADD_Q    (Hart *hart, const Instruction &instr);
Exception FMSUB_Q    (Hart *hart, const Instruction &instr);
Exception FNMSUB_Q   (Hart *hart, const Instruction &instr);
Exception FNMADD_Q   (Hart *hart, const Instruction &instr);
Exception INVALID    (Hart *hart, const Instruction &instr);

// clang-format on

} // namespace iexec
} // namespace rvsim

#endif // SIMULATOR_INSTRUCTION_EXEC_INSTRUCTION_EXEC_H
