/*
 * This file is autogenerated by 'generate.py' script from risc-v.yaml file
 * Do not try to change anything in this file
 ***********************************************************
 * Written by Glaz Roman (Vokerlee)
 */

#include "common/utils/bit_ops.h"
#include "instruction.h"

namespace rvsim {

void Instruction::Decode(insn_size_t insn)
{
    word_t var_bits_0 = bitops::GetBits<6, 0>(insn);
    if (var_bits_0 == 99) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::BEQ;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::BNE;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InstructionId::BLT;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InstructionId::BGE;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 6) {
            id_ = InstructionId::BLTU;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InstructionId::BGEU;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 103) {
        id_ = InstructionId::JALR;

        attributes_.is_branch = true;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        rs1_ |= (bitops::GetBits<19, 15>(insn));
        imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

        return;
    }

    if (var_bits_0 == 111) {
        id_ = InstructionId::JAL;

        attributes_.is_branch = true;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        imm_ |= (bitops::GetBits<30, 21>(insn)) << 1;
        imm_ |= (bitops::GetBits<20, 20>(insn)) << 11;
        imm_ |= (bitops::GetBits<19, 12>(insn)) << 12;
        imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 20;

        return;
    }

    if (var_bits_0 == 55) {
        id_ = InstructionId::LUI;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        imm_ |= bitops::SignExtend<20, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 12>(insn)) << 12;

        return;
    }

    if (var_bits_0 == 23) {
        id_ = InstructionId::AUIPC;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        imm_ |= bitops::SignExtend<20, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 12>(insn)) << 12;

        return;
    }

    if (var_bits_0 == 19) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::ADDI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::SLLI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InstructionId::SLTI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::SLTIU;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InstructionId::XORI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            word_t var_bits_2 = bitops::GetBits<31, 26>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::SRLI;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            if (var_bits_2 == 16) {
                id_ = InstructionId::SRAI;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 6) {
            id_ = InstructionId::ORI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InstructionId::ANDI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 51) {
        word_t var_bits_1 = bitops::GetBits<31, 25>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::ADD;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::SLL;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::SLT;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::SLTU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 4) {
                id_ = InstructionId::XOR;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InstructionId::SRL;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 6) {
                id_ = InstructionId::OR;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 7) {
                id_ = InstructionId::AND;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 32) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::SUB;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InstructionId::SRA;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::MUL;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::MULH;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::MULHSU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::MULHU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 4) {
                id_ = InstructionId::DIV;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InstructionId::DIVU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 6) {
                id_ = InstructionId::REM;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 7) {
                id_ = InstructionId::REMU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 27) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::ADDIW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::SLLIW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            word_t var_bits_2 = bitops::GetBits<31, 25>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::SRLIW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            if (var_bits_2 == 32) {
                id_ = InstructionId::SRAIW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 59) {
        word_t var_bits_1 = bitops::GetBits<31, 25>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::ADDW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::SLLW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InstructionId::SRLW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 32) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::SUBW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InstructionId::SRAW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::MULW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 4) {
                id_ = InstructionId::DIVW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InstructionId::DIVUW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 6) {
                id_ = InstructionId::REMW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 7) {
                id_ = InstructionId::REMUW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 3) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::LB;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::LH;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InstructionId::LW;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::LD;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InstructionId::LBU;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InstructionId::LHU;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 6) {
            id_ = InstructionId::LWU;

            attributes_.is_load = true;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 35) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::SB;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::SH;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InstructionId::SW;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::SD;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 15) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::FENCE;

            imm_ |= bitops::SignExtend<4, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 28>(insn));
            imm_ |= (bitops::GetBits<27, 24>(insn));
            imm_ |= (bitops::GetBits<23, 20>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rd_ |= (bitops::GetBits<11, 7>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::FENCE_I;

            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rd_ |= (bitops::GetBits<11, 7>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 47) {
        word_t var_bits_1 = bitops::GetBits<31, 27>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOADD_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOADD_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 4) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOXOR_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOXOR_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 8) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOOR_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOOR_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 12) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOAND_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOAND_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 16) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOMIN_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOMIN_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 20) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOMAX_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOMAX_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 24) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOMINU_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOMINU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 28) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOMAXU_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOMAXU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::AMOSWAP_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::AMOSWAP_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 2) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 2) {
                    id_ = InstructionId::LR_W;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));
                    imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                    return;
                }

                if (var_bits_3 == 3) {
                    id_ = InstructionId::LR_D;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));
                    imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InstructionId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 3) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InstructionId::SC_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::SC_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 115) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<31, 25>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<24, 15>(insn);
                if (var_bits_3 == 0) {
                    id_ = InstructionId::ECALL;

                    attributes_.is_branch = true;

                    return;
                }

                if (var_bits_3 == 32) {
                    id_ = InstructionId::EBREAK;

                    return;
                }

                if (var_bits_3 == 64) {
                    id_ = InstructionId::URET;

                    return;
                }

                /* Instruction wasn't found */
                id_ = InstructionId::INVALID_ID;
                return;
            }

            if (var_bits_2 == 8) {
                word_t var_bits_3 = bitops::GetBits<24, 15>(insn);
                if (var_bits_3 == 64) {
                    id_ = InstructionId::SRET;

                    attributes_.mode = Mode::SUPERVISOR_MODE;

                    return;
                }

                if (var_bits_3 == 160) {
                    id_ = InstructionId::WFI;

                    attributes_.mode = Mode::MACHINE_MODE;

                    return;
                }

                /* Instruction wasn't found */
                id_ = InstructionId::INVALID_ID;
                return;
            }

            if (var_bits_2 == 24) {
                id_ = InstructionId::MRET;

                attributes_.mode = Mode::MACHINE_MODE;

                return;
            }

            if (var_bits_2 == 61) {
                id_ = InstructionId::DRET;

                return;
            }

            if (var_bits_2 == 9) {
                id_ = InstructionId::SFENCE_VMA;

                attributes_.mode = Mode::SUPERVISOR_MODE;

                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 17) {
                id_ = InstructionId::HFENCE_VVMA;

                attributes_.mode = Mode::HYPERVISOR_MODE;

                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 49) {
                id_ = InstructionId::HFENCE_GVMA;

                attributes_.mode = Mode::HYPERVISOR_MODE;

                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::CSRRW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InstructionId::CSRRS;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::CSRRC;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InstructionId::CSRRWI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 6) {
            id_ = InstructionId::CSRRSI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InstructionId::CSRRCI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 83) {
        word_t var_bits_1 = bitops::GetBits<31, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::FADD_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InstructionId::FSUB_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 8) {
            id_ = InstructionId::FMUL_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 12) {
            id_ = InstructionId::FDIV_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 16) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FSGNJ_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FSGNJN_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FSGNJX_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 20) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FMIN_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FMAX_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 44) {
            id_ = InstructionId::FSQRT_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::FADD_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InstructionId::FSUB_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 9) {
            id_ = InstructionId::FMUL_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 13) {
            id_ = InstructionId::FDIV_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 17) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FSGNJ_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FSGNJN_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FSGNJX_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 21) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FMIN_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FMAX_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 32) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_S_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_S_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 33) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_D_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_D_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 45) {
            id_ = InstructionId::FSQRT_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FADD_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InstructionId::FSUB_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 11) {
            id_ = InstructionId::FMUL_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 15) {
            id_ = InstructionId::FDIV_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 19) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FSGNJ_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FSGNJN_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FSGNJX_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 23) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FMIN_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FMAX_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 35) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_Q_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_Q_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 47) {
            id_ = InstructionId::FSQRT_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 80) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FLE_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FLT_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FEQ_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 81) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FLE_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FLT_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FEQ_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 83) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FLE_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FLT_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FEQ_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 96) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_W_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_WU_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FCVT_L_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_LU_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 112) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 0) {
                    id_ = InstructionId::FMV_X_W;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                if (var_bits_3 == 1) {
                    id_ = InstructionId::FCLASS_S;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InstructionId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 97) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_W_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_WU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FCVT_L_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_LU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 113) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 0) {
                    id_ = InstructionId::FMV_X_D;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                if (var_bits_3 == 1) {
                    id_ = InstructionId::FCLASS_D;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InstructionId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 99) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_W_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_WU_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FCVT_L_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_LU_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 115) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 0) {
                    id_ = InstructionId::FMV_X_Q;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                if (var_bits_3 == 1) {
                    id_ = InstructionId::FCLASS_Q;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InstructionId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 104) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_S_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_S_WU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FCVT_S_L;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_S_LU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 120) {
            id_ = InstructionId::FMV_W_X;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));

            return;
        }

        if (var_bits_1 == 105) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_D_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_D_WU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FCVT_D_L;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_D_LU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 121) {
            id_ = InstructionId::FMV_D_X;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));

            return;
        }

        if (var_bits_1 == 107) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InstructionId::FCVT_Q_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InstructionId::FCVT_Q_WU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InstructionId::FCVT_Q_L;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InstructionId::FCVT_Q_LU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InstructionId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 123) {
            id_ = InstructionId::FMV_Q_X;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 7) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 2) {
            id_ = InstructionId::FLW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FLD;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InstructionId::FLQ;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 39) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 2) {
            id_ = InstructionId::FSW;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FSD;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InstructionId::FSQ;

            attributes_.is_store = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 67) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::FMADD_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::FMADD_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FMADD_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 71) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::FMSUB_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::FMSUB_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FMSUB_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 75) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::FNMSUB_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::FNMSUB_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FNMSUB_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 79) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InstructionId::FNMADD_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InstructionId::FNMADD_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InstructionId::FNMADD_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InstructionId::INVALID_ID;
        return;
    }

    /* Instruction wasn't found */
    id_ = InstructionId::INVALID_ID;
    return;
}

} // namespace rvsim
