/*
 * This file is autogenerated by 'generate.py' script from risc-v.yaml file
 * Do not try to change anything in this file
 ***********************************************************
 * Written by Glaz Roman (Vokerlee)
 */

#include "common/utils/bit_ops.h"
#include "instruction.h"

namespace rvsim {

void Insn::Decode(insn_size_t insn)
{
    word_t var_bits_0 = bitops::GetBits<6, 0>(insn);
    if (var_bits_0 == 99) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::BEQ;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::BNE;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InsnId::BLT;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InsnId::BGE;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 6) {
            id_ = InsnId::BLTU;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InsnId::BGEU;

            attributes_.is_branch = true;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 8>(insn)) << 1;
            imm_ |= (bitops::GetBits<30, 25>(insn)) << 5;
            imm_ |= (bitops::GetBits<7, 7>(insn)) << 11;
            imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 12;

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 103) {
        id_ = InsnId::JALR;

        attributes_.is_branch = true;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        rs1_ |= (bitops::GetBits<19, 15>(insn));
        imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

        return;
    }

    if (var_bits_0 == 111) {
        id_ = InsnId::JAL;

        attributes_.is_branch = true;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        imm_ |= (bitops::GetBits<30, 21>(insn)) << 1;
        imm_ |= (bitops::GetBits<20, 20>(insn)) << 11;
        imm_ |= (bitops::GetBits<19, 12>(insn)) << 12;
        imm_ |= bitops::SignExtend<1, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 31>(insn)) << 20;

        return;
    }

    if (var_bits_0 == 55) {
        id_ = InsnId::LUI;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        imm_ |= bitops::SignExtend<20, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 12>(insn)) << 12;

        return;
    }

    if (var_bits_0 == 23) {
        id_ = InsnId::AUIPC;

        rd_ |= (bitops::GetBits<11, 7>(insn));
        imm_ |= bitops::SignExtend<20, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 12>(insn)) << 12;

        return;
    }

    if (var_bits_0 == 19) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::ADDI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::SLLI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InsnId::SLTI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::SLTIU;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InsnId::XORI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            word_t var_bits_2 = bitops::GetBits<31, 26>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::SRLI;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            if (var_bits_2 == 16) {
                id_ = InsnId::SRAI;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 6) {
            id_ = InsnId::ORI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InsnId::ANDI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 51) {
        word_t var_bits_1 = bitops::GetBits<31, 25>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::ADD;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::SLL;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::SLT;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::SLTU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 4) {
                id_ = InsnId::XOR;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InsnId::SRL;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 6) {
                id_ = InsnId::OR;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 7) {
                id_ = InsnId::AND;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 32) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::SUB;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InsnId::SRA;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::MUL;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::MULH;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::MULHSU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::MULHU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 4) {
                id_ = InsnId::DIV;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InsnId::DIVU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 6) {
                id_ = InsnId::REM;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 7) {
                id_ = InsnId::REMU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 27) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::ADDIW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::SLLIW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            word_t var_bits_2 = bitops::GetBits<31, 25>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::SRLIW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            if (var_bits_2 == 32) {
                id_ = InsnId::SRAIW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 59) {
        word_t var_bits_1 = bitops::GetBits<31, 25>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::ADDW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::SLLW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InsnId::SRLW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 32) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::SUBW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InsnId::SRAW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::MULW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 4) {
                id_ = InsnId::DIVW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 5) {
                id_ = InsnId::DIVUW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 6) {
                id_ = InsnId::REMW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 7) {
                id_ = InsnId::REMUW;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 3) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::LB;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::LH;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InsnId::LW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::LD;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InsnId::LBU;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InsnId::LHU;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 6) {
            id_ = InsnId::LWU;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 35) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::SB;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::SH;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InsnId::SW;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::SD;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 15) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::FENCE;

            imm_ |= bitops::SignExtend<4, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 28>(insn));
            imm_ |= (bitops::GetBits<27, 24>(insn));
            imm_ |= (bitops::GetBits<23, 20>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rd_ |= (bitops::GetBits<11, 7>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::FENCE_I;

            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rd_ |= (bitops::GetBits<11, 7>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 47) {
        word_t var_bits_1 = bitops::GetBits<31, 27>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOADD_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOADD_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 4) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOXOR_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOXOR_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 8) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOOR_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOOR_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 12) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOAND_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOAND_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 16) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOMIN_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOMIN_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 20) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOMAX_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOMAX_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 24) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOMINU_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOMINU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 28) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOMAXU_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOMAXU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::AMOSWAP_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::AMOSWAP_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 2) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 2) {
                    id_ = InsnId::LR_W;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));
                    imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                    return;
                }

                if (var_bits_3 == 3) {
                    id_ = InsnId::LR_D;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));
                    imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InsnId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 3) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 2) {
                id_ = InsnId::SC_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::SC_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));
                imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 115) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 0) {
            word_t var_bits_2 = bitops::GetBits<31, 25>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<24, 15>(insn);
                if (var_bits_3 == 0) {
                    id_ = InsnId::ECALL;

                    attributes_.is_branch = true;

                    return;
                }

                if (var_bits_3 == 32) {
                    id_ = InsnId::EBREAK;

                    return;
                }

                if (var_bits_3 == 64) {
                    id_ = InsnId::URET;

                    return;
                }

                /* Instruction wasn't found */
                id_ = InsnId::INVALID_ID;
                return;
            }

            if (var_bits_2 == 8) {
                word_t var_bits_3 = bitops::GetBits<24, 15>(insn);
                if (var_bits_3 == 64) {
                    id_ = InsnId::SRET;

                    return;
                }

                if (var_bits_3 == 160) {
                    id_ = InsnId::WFI;

                    return;
                }

                /* Instruction wasn't found */
                id_ = InsnId::INVALID_ID;
                return;
            }

            if (var_bits_2 == 24) {
                id_ = InsnId::MRET;

                return;
            }

            if (var_bits_2 == 61) {
                id_ = InsnId::DRET;

                return;
            }

            if (var_bits_2 == 9) {
                id_ = InsnId::SFENCE_VMA;

                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 17) {
                id_ = InsnId::HFENCE_VVMA;

                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 49) {
                id_ = InsnId::HFENCE_GVMA;

                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::CSRRW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 2) {
            id_ = InsnId::CSRRS;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::CSRRC;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InsnId::CSRRWI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 6) {
            id_ = InsnId::CSRRSI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InsnId::CSRRCI;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 83) {
        word_t var_bits_1 = bitops::GetBits<31, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::FADD_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InsnId::FSUB_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 8) {
            id_ = InsnId::FMUL_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 12) {
            id_ = InsnId::FDIV_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 16) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FSGNJ_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FSGNJN_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FSGNJX_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 20) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FMIN_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FMAX_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 44) {
            id_ = InsnId::FSQRT_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::FADD_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 5) {
            id_ = InsnId::FSUB_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 9) {
            id_ = InsnId::FMUL_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 13) {
            id_ = InsnId::FDIV_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 17) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FSGNJ_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FSGNJN_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FSGNJX_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 21) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FMIN_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FMAX_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 32) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_S_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_S_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 33) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_D_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_D_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 45) {
            id_ = InsnId::FSQRT_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FADD_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 7) {
            id_ = InsnId::FSUB_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 11) {
            id_ = InsnId::FMUL_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 15) {
            id_ = InsnId::FDIV_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 19) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FSGNJ_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FSGNJN_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FSGNJX_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 23) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FMIN_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FMAX_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 35) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_Q_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_Q_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 47) {
            id_ = InsnId::FSQRT_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 80) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FLE_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FLT_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FEQ_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 81) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FLE_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FLT_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FEQ_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 83) {
            word_t var_bits_2 = bitops::GetBits<14, 12>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FLE_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FLT_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FEQ_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rs2_ |= (bitops::GetBits<24, 20>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 96) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_W_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_WU_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FCVT_L_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_LU_S;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 112) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 0) {
                    id_ = InsnId::FMV_X_W;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                if (var_bits_3 == 1) {
                    id_ = InsnId::FCLASS_S;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InsnId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 97) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_W_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_WU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FCVT_L_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_LU_D;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 113) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 0) {
                    id_ = InsnId::FMV_X_D;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                if (var_bits_3 == 1) {
                    id_ = InsnId::FCLASS_D;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InsnId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 99) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_W_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_WU_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FCVT_L_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_LU_Q;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 115) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                word_t var_bits_3 = bitops::GetBits<14, 12>(insn);
                if (var_bits_3 == 0) {
                    id_ = InsnId::FMV_X_Q;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                if (var_bits_3 == 1) {
                    id_ = InsnId::FCLASS_Q;

                    rd_ |= (bitops::GetBits<11, 7>(insn));
                    rs1_ |= (bitops::GetBits<19, 15>(insn));

                    return;
                }

                /* Instruction wasn't found */
                id_ = InsnId::INVALID_ID;
                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 104) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_S_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_S_WU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FCVT_S_L;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_S_LU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 120) {
            id_ = InsnId::FMV_W_X;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));

            return;
        }

        if (var_bits_1 == 105) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_D_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_D_WU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FCVT_D_L;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_D_LU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 121) {
            id_ = InsnId::FMV_D_X;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));

            return;
        }

        if (var_bits_1 == 107) {
            word_t var_bits_2 = bitops::GetBits<24, 20>(insn);
            if (var_bits_2 == 0) {
                id_ = InsnId::FCVT_Q_W;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 1) {
                id_ = InsnId::FCVT_Q_WU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 2) {
                id_ = InsnId::FCVT_Q_L;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            if (var_bits_2 == 3) {
                id_ = InsnId::FCVT_Q_LU;

                rd_ |= (bitops::GetBits<11, 7>(insn));
                rs1_ |= (bitops::GetBits<19, 15>(insn));
                rm_ |= (bitops::GetBits<14, 12>(insn));

                return;
            }

            /* Instruction wasn't found */
            id_ = InsnId::INVALID_ID;
            return;
        }

        if (var_bits_1 == 123) {
            id_ = InsnId::FMV_Q_X;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 7) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 2) {
            id_ = InsnId::FLW;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FLD;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InsnId::FLQ;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            imm_ |= bitops::SignExtend<12, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 20>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 39) {
        word_t var_bits_1 = bitops::GetBits<14, 12>(insn);
        if (var_bits_1 == 2) {
            id_ = InsnId::FSW;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FSD;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        if (var_bits_1 == 4) {
            id_ = InsnId::FSQ;

            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            imm_ |= (bitops::GetBits<11, 7>(insn));
            imm_ |= bitops::SignExtend<7, bitops::BitSizeof<word_t>()>(bitops::GetBits<31, 25>(insn)) << 5;

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 67) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::FMADD_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::FMADD_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FMADD_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 71) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::FMSUB_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::FMSUB_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FMSUB_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 75) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::FNMSUB_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::FNMSUB_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FNMSUB_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    if (var_bits_0 == 79) {
        word_t var_bits_1 = bitops::GetBits<26, 25>(insn);
        if (var_bits_1 == 0) {
            id_ = InsnId::FNMADD_S;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 1) {
            id_ = InsnId::FNMADD_D;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        if (var_bits_1 == 3) {
            id_ = InsnId::FNMADD_Q;

            rd_ |= (bitops::GetBits<11, 7>(insn));
            rs1_ |= (bitops::GetBits<19, 15>(insn));
            rs2_ |= (bitops::GetBits<24, 20>(insn));
            rs3_ |= (bitops::GetBits<31, 27>(insn));
            rm_ |= (bitops::GetBits<14, 12>(insn));

            return;
        }

        /* Instruction wasn't found */
        id_ = InsnId::INVALID_ID;
        return;
    }

    /* Instruction wasn't found */
    id_ = InsnId::INVALID_ID;
    return;
}

} // namespace rvsim
